### PR TITLE
Fix local storage implementation when using keys containing directories

### LINKED ISSUE #311: LocalStorageOperations: When key is on form folder/filename, FileNotFoundException is thrown
### Expected Behavior

I'm using the below method with `LocalStorageOperations` and the following value for key: `20230725T012342/test-file.xml`. This should be OK according to the doc below.

```
    /**
     * @param bytes the source byte array.
     * @param key the key under which the file will be stored (<code>path/to/file</code>)
     * @param contentType the content type of the file to store.
     * @return An {@link UploadRequest} from the given parameters.
     */
    @NonNull
    static UploadRequest fromBytes(@NonNull byte[] bytes,
                                   @NonNull String key,
                                   @NonNull String contentType) {
        return new BytesUploadRequest(bytes, key, contentType);
    }
```

### Actual Behaviour

I'm getting this stack trace when using `20230725T012342/test-file.xml` as blob name.

```
/tmp/micronaut-object-storage-local3571089902645606140/20230725T012342/test-file.xml (No such file or directory)
java.io.FileNotFoundException: /tmp/micronaut-object-storage-local3571089902645606140/20230725T012342/test-file.xml (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at io.micronaut.objectstorage.local.LocalStorageOperations.storeFile(LocalStorageOperations.java:189)
	at io.micronaut.objectstorage.local.LocalStorageOperations.storeFile(LocalStorageOperations.java:184)
	at io.micronaut.objectstorage.local.LocalStorageOperations.upload(LocalStorageOperations.java:81)
	at io.micronaut.objectstorage.local.LocalStorageOperations.upload(LocalStorageOperations.java:74)
```

### Steps To Reproduce

```
fun ObjectStorageOperations<*, *, *>.createTestBlob(): UploadResponse<out Any> = this.upload(
    UploadRequest.fromBytes(
        "a".repeat(100).toByteArray(),
        "directory/filename.txt"
    )
)
```

I'm able to fix this in source with this code in LocalStorageOperations.java, but then LocalStorageOperations#listObjects is not working as expected by returning just the folder name. LocalStorageOperations#retrieve is working though.
```
private Path storeFile(String key, InputStream inputStream) {
    final File file = Paths.get(configuration.getPath().toString(), key).toFile();

    final Path parentPath = Path.of(file.getParent());
    if (Files.notExists(parentPath)) {
        try {
            Files.createDirectories(parentPath);
        } catch (IOException e) {
            throw new ObjectStorageException("Error creating directory: " + parentPath, e);
        }
    }

    try (OutputStream fileOut = new FileOutputStream(file)) {
        inputStream.transferTo(fileOut);
        return file.toPath();
    } catch (IOException e) {
        throw new ObjectStorageException("Error copying file to: " + file, e);
    }
}
```

If fixing `listObjects` it would be nice if folder names can end with `/` so we can do like we do with `com.google.cloud.storage.BlobId`
```
fun BlobId.isFile(): Boolean = !this.name.endsWith("/")
```

### Environment Information

Ubuntu 22.04
JDK 17
Micronaut 4.0.1
micronaut-object-storage-local:2.0.1
Kotlin:1.9.0

### Example Application

_No response_

### Version

4.0.1

### PR DESCRIPTION
**Pull request by alvarosanchez**
Fixes #311

### CODE REVIEW

File: object-storage-local/src/main/java/io/micronaut/objectstorage/local/LocalStorageOperations.java [hunk 1]
```diff
@@ -206,6 +207,7 @@ private void storeMetadata(String key, Map<String, String> metadata) {
         Properties metadataProperties = new Properties();
         metadataProperties.putAll(metadata);
         Path metadataFilePath = Paths.get(metadataPath.toString(), key);
+        metadataFilePath.getParent().toFile().mkdirs();
```
Comment (melix) [inline object-storage-local/src/main/java/io/micronaut/objectstorage/local/LocalStorageOperations.java:210]: I think security-wise, `Files.createDirectories(...)` is safer.

File: object-storage-tck/src/main/groovy/io/micronaut/objectstorage/ObjectStorageOperationsSpecification.groovy [hunk 2]
```diff
@@ -77,7 +77,12 @@ abstract class ObjectStorageOperationsSpecification extends Specification {
         when: 'updating the file'
         if (emulatorSupportsUpdate()) {
             path.toFile().text = NEW_TEXT
-            uploadRequest = UploadRequest.fromPath(path)
+            if (key.contains(File.separator)) {
```
Comment (melix) [inline object-storage-tck/src/main/groovy/io/micronaut/objectstorage/ObjectStorageOperationsSpecification.groovy:80]: I wonder about the `File.separator` here. In upload requests are you supposed to use OS specific separators? Wouldn't it always be `/`?

**Review by melix — APPROVED** [review]

File: object-storage-tck/src/main/groovy/io/micronaut/objectstorage/ObjectStorageOperationsSpecification.groovy (hunk 2 above)
Comment (alvarosanchez) [reply object-storage-tck/src/main/groovy/io/micronaut/objectstorage/ObjectStorageOperationsSpecification.groovy]: Although you are correct, note this is mostly test logic
